### ISSUE TITLE
ARM docker image issue

### ISSUE THREAD

**Issue by raaghulr** [antl3x/codeplot#2]
Hi Team,
I am trying to get the project for arm machine using docker,

**codeplot-front The requested image's platform (linux/amd64) does not match the detected host platform **(linux/arm64/v8)** and no specific platform was requested 0.0s 
Attaching to codeplot-api-1, codeplot-front-1
codeplot-api-1    | exec /usr/local/bin/docker-entrypoint.sh: exec format error
codeplot-api-1 exited with code 1**

Any other information needed, plz let know

**Comment by antl3x** [comment]
Hey @raaghulr !

We now have ARM64 image support available on Docker Hub. Could you please verify this? 

Thank you

**Comment by antl3x** [comment]
Closing, since we already support ARM images.
