### ISSUE TITLE
white screen when deploying using docker 

### ISSUE THREAD

**Issue by mz0in** [antl3x/codeplot#3]
the deployment is successful , but when opening new file it only a white space 

<img width="1208" alt="image" src="https://github.com/codeplot-co/codeplot/assets/5844695/7597c71d-9584-4421-9b9d-81c5904addcf">

**Comment by antl3x** [comment]
Can you paste the console output? Also please could you check the logs of the codeplot-api docker container.

**Comment by mz0in** [comment]
> @codeplot/api@1.0.0 server.start /opt/minirepos/@codeplot-api
> zx _scripts/server.start.mjs
Starting server in selfhost mode...
$ node ./dist/main.js
running at on port 9108

  ---------

/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2024/03/06 00:15:30 [notice] 1#1: using the "epoll" event method
2024/03/06 00:15:30 [notice] 1#1: nginx/1.25.4
2024/03/06 00:15:30 [notice] 1#1: built by gcc 12.2.1 20220924 (Alpine 12.2.1_git20220924-r10) 
2024/03/06 00:15:30 [notice] 1#1: OS: Linux 5.15.0-97-generic
2024/03/06 00:15:30 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2024/03/06 00:15:30 [notice] 1#1: start worker processes
2024/03/06 00:15:30 [notice] 1#1: start worker process 30
2024/03/06 00:15:30 [notice] 1#1: start worker process 31
2024/03/06 00:15:30 [notice] 1#1: start worker process 32
2024/03/06 00:15:30 [notice] 1#1: start worker process 33
2024/03/06 00:15:30 [notice] 1#1: start worker process 34
2024/03/06 00:15:30 [notice] 1#1: start worker process 35
2024/03/06 00:15:30 [notice] 1#1: start worker process 36
2024/03/06 00:15:30 [notice] 1#1: start worker process 37
172.24.0.1 - - [06/Mar/2024:00:16:08 +0000] "GET / HTTP/1.1" 200 877 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4 Safari/605.1.15" "46.196.145.157"
172.24.0.1 - - [06/Mar/2024:00:16:12 +0000] "GET / HTTP/1.1" 200 877 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4 Safari/605.1.15" "46.196.145.157"
172.24.0.1 - - [06/Mar/2024:00:17:08 +0000] "GET / HTTP/1.1" 200 877 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4 Safari/605.1.15" "46.196.145.157"
172.24.0.1 - - [06/Mar/2024:02:03:09 +0000] "GET /assets/Upload-FsFc-7rE.js HTTP/1.1" 304 0 "https://code.xxxx.io/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4 Safari/605.1.15" "46.196.145.157"
172.24.0.1 - - [06/Mar/2024:02:03:16 +0000] "GET / HTTP/1.1" 200 877 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4 Safari/605.1.15" "46.196.145.157"
172.24.0.1 - - [06/Mar/2024:02:03:21 +0000] "GET / HTTP/1.1" 200 877 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36" "46.196.145.157"
172.24.0.1 - - [06/Mar/2024:02:03:21 +0000] "GET /assets/index-XC76B3Lv.js HTTP/1.1" 304 0 "https://code.xxxx.io/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36" "46.196.145.157"
172.24.0.1 - - [06/Mar/2024:02:03:21 +0000] "GET /assets/index-3EgHvDbe.css HTTP/1.1" 304 0 "https://code.xxxx.io/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36" "46.196.145.157"
172.24.0.1 - - [06/Mar/2024:02:03:23 +0000] "GET /assets/CreateNew-CzgaJSSY.js HTTP/1.1" 304 0 "https://code.xxxx.io/assets/index-XC76B3Lv.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36" "46.196.145.157"
172.24.0.1 - - [06/Mar/2024:02:03:23 +0000] "GET /arrow-diagonal.svg HTTP/1.1" 304 0 "https://code.xxxx.io/assets/index-3EgHvDbe.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36" "46.196.145.157"
172.24.0.1 - - [06/Mar/2024:02:03:23 +0000] "GET /favicon.png HTTP/1.1" 304 0 "https://code.xxxx.io/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36" "46.196.145.157"
172.24.0.1 - - [06/Mar/2024:03:01:01 +0000] "GET / HTTP/1.1" 200 877 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko)" "46.196.145.157"
2024/03/06 03:01:01 [error] 33#33: *5 open() "/usr/share/nginx/html/apple-touch-icon-precomposed.png" failed (2: No such file or directory), client: 172.24.0.1, server: localhost, request: "GET /apple-touch-icon-precomposed.png HTTP/1.1", host: "code.xxxx.io"
172.24.0.1 - - [06/Mar/2024:03:01:01 +0000] "GET /apple-touch-icon-precomposed.png HTTP/1.1" 404 153 "-" "Safari/19618.1.15.11.12 CFNetwork/1494.0.7 Darwin/23.4.0" "46.196.145.157"
172.24.0.1 - - [06/Mar/2024:03:01:01 +0000] "GET /apple-touch-icon.png HTTP/1.1" 404 153 "-" "Safari/19618.1.15.11.12 CFNetwork/1494.0.7 Darwin/23.4.0" "46.196.145.157"
2024/03/06 03:01:01 [error] 33#33: *5 open() "/usr/share/nginx/html/apple-touch-icon.png" failed (2: No such file or directory), client: 172.24.0.1, server: localhost, request: "GET /apple-touch-icon.png HTTP/1.1", host: "code.xxxx.io"
172.24.0.1 - - [06/Mar/2024:03:01:01 +0000] "GET / HTTP/1.1" 200 877 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 17_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4 Mobile/15E148 Safari/604.1" "46.196.145.157"
172.24.0.1 - - [06/Mar/2024:03:05:01 +0000] "GET / HTTP/1.1" 200 877 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4 Safari/605.1.15" "46.196.145.157"
172.24.0.1 - - [06/Mar/2024:03:45:16 +0000] "GET / HTTP/1.1" 200 877 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4 Safari/605.1.15" "46.196.145.157"

----

<img width="1137" alt="image" src="https://github.com/codeplot-co/codeplot/assets/5844695/adff9232-6200-4ed5-a455-4abe191ac868">

**Comment by antl3x** [comment]
I've attempted to replicate the issue on my end, and everything appears to be functioning correctly.

Are you executing the containers on your local machine or localhost? If not, that might be the underlying issue.

I noticed in the logs that you're utilizing the hostname "https://code.xxxx.io/", which is distinct from localhost. The container is designed to operate exclusively in a localhost environment and is not intended for use in cloud-based environments.

**Comment by mz0in** [comment]
ok that is the point , I'm deploying on remote server on the cloud  , and the "[code.xxxx.io] is just that I masked my domain since it's public here 
any plan to support cloud deployment

**Comment by antl3x** [comment]
Yes! 

Any special need for personal usage on the cloud? We plan to support but for commercial use-cases.

**Comment by mz0in** [comment]
I think adding further such as user login , team collaboration management with different level such as editor , viewers , etc

**Comment by antl3x** [comment]
Of course! Will keep your feedback on roadmap notes. Thanks
